### PR TITLE
Implement winbuilder queue

### PR DESCRIPTION
**Pull request by fmichonneau**
as suggested in #40

### CODE REVIEW

**Comment by krlmlr** [comment]
Thanks, works for me!

Can we return `date` and `time` as one `timestamp` column of `POSIXct` type? The `version` could be a `package_version` object too.

Did you need to adjust for a time offset?

**Comment by krlmlr** [comment]
With an empty queue, should we return a zero-row tibble nevertheless, for type stability? What do the other functions do? We could special-case the output with a subclass if necessary.

**Comment by fmichonneau** [comment]
Thanks, yes that's a good idea. In the package, the only other point of comparison would be the output of `cran_incoming` but it should also be changed there. I changed it here and will change it in the other function once this is merged. 

By the way, is this the recommended pattern to create zero-row tibbles? (see [this commit](https://github.com/fmichonneau/foghorn/pull/41/commits/aded8d9edb8f455c3862617ab089963c2536de22))

**Comment by krlmlr** [comment]
One way to solve this corner case is to provide a constructor with the correctly typed defaults. Ensure that you use only the constructor to create these tibbles.

```r
new_foo <- function(bar = character(), baz = integer()) {
  stopifnot(is.character(bar))
  stopifnot(is.integer(baz))
  tibble(bar, baz)
}
```

If you have a lot of those, I'm sure it's possible to implement a generator function that creates these helpers:

```r
make_new <- function(...) { ...}
make_new(bar = character(), baz = integer())
#> function(bar = character(), baz = integer()) {
#>   stopifnot(vctrs::vec_is(bar, character()))
#>   stopifnot(vctrs::vec_is(baz, integer()))
#>   tibble(bar, baz)
#> }
```

**Comment by krlmlr** [comment]
I think such a constructor would be a great fit for the dm package ;-)

**Comment by fmichonneau** [comment]
Thank you for the suggestions and the feedback on this!

**Comment by krlmlr** [comment]
Thank you so much, I'm a regular user now, works great! Time zones are shown correctly on my system (CEST).

**Pull request merged**
